/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AboutRouteImport } from './routes/about'
import { Route as NowRouteImport } from './routes/now'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as ExperienceIndexRouteImport } from './routes/experience/index'
import { Route as ExperienceCompanyRouteImport } from './routes/experience/$company'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const NowRoute = NowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceIndexRoute = ExperienceIndexRouteImport.update({
  id: '/experience/',
  path: '/experience/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceCompanyRoute = ExperienceCompanyRouteImport.update({
  id: '/experience/$company',
  path: '/experience/$company',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/now': typeof NowRoute
  '/writing': typeof WritingRoute
  '/experience/$company': typeof ExperienceCompanyRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/experience/': typeof ExperienceIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/now': typeof NowRoute
  '/writing': typeof WritingRoute
  '/experience/$company': typeof ExperienceCompanyRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/experience': typeof ExperienceIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/now': typeof NowRoute
  '/writing': typeof WritingRoute
  '/experience/$company': typeof ExperienceCompanyRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/experience/': typeof ExperienceIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/now'
    | '/writing'
    | '/experience/$company'
    | '/products/$slug'
    | '/experience/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/now'
    | '/writing'
    | '/experience/$company'
    | '/products/$slug'
    | '/experience'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/now'
    | '/writing'
    | '/experience/$company'
    | '/products/$slug'
    | '/experience/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  NowRoute: typeof NowRoute
  WritingRoute: typeof WritingRoute
  ExperienceCompanyRoute: typeof ExperienceCompanyRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ExperienceIndexRoute: typeof ExperienceIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now': {
      id: '/now'
      path: '/now'
      fullPath: '/now'
      preLoaderRoute: typeof NowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/': {
      id: '/experience/'
      path: '/experience'
      fullPath: '/experience/'
      preLoaderRoute: typeof ExperienceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/$company': {
      id: '/experience/$company'
      path: '/experience/$company'
      fullPath: '/experience/$company'
      preLoaderRoute: typeof ExperienceCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  NowRoute: NowRoute,
  WritingRoute: WritingRoute,
  ExperienceCompanyRoute: ExperienceCompanyRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ExperienceIndexRoute: ExperienceIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
