/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as RedirectsRouteImport } from './routes/[_]redirects'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as NowRouteImport } from './routes/now'
import { Route as ExperienceIndexRouteImport } from './routes/experience/index'
import { Route as ExperienceCompanyRouteImport } from './routes/experience/$company'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as WritingIndexRouteImport } from './routes/writing/index'
import { Route as WritingSlugRouteImport } from './routes/writing/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectsRoute = RedirectsRouteImport.update({
  id: '/_redirects',
  path: '/_redirects',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const NowRoute = NowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceIndexRoute = ExperienceIndexRouteImport.update({
  id: '/experience/',
  path: '/experience/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceCompanyRoute = ExperienceCompanyRouteImport.update({
  id: '/experience/$company',
  path: '/experience/$company',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/writing/$slug',
  path: '/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/_redirects': typeof RedirectsRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/now': typeof NowRoute
  '/experience/$company': typeof ExperienceCompanyRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/experience/': typeof ExperienceIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/_redirects': typeof RedirectsRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/now': typeof NowRoute
  '/experience/$company': typeof ExperienceCompanyRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/experience': typeof ExperienceIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/writing': typeof WritingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/_redirects': typeof RedirectsRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/now': typeof NowRoute
  '/experience/$company': typeof ExperienceCompanyRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/experience/': typeof ExperienceIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/_redirects'
    | '/about'
    | '/contact'
    | '/llms.txt'
    | '/now'
    | '/experience/$company'
    | '/projects/$slug'
    | '/writing/$slug'
    | '/experience/'
    | '/projects/'
    | '/writing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/_redirects'
    | '/about'
    | '/contact'
    | '/llms.txt'
    | '/now'
    | '/experience/$company'
    | '/projects/$slug'
    | '/writing/$slug'
    | '/experience'
    | '/projects'
    | '/writing'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/_redirects'
    | '/about'
    | '/contact'
    | '/llms.txt'
    | '/now'
    | '/experience/$company'
    | '/projects/$slug'
    | '/writing/$slug'
    | '/experience/'
    | '/projects/'
    | '/writing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  RedirectsRoute: typeof RedirectsRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  NowRoute: typeof NowRoute
  ExperienceCompanyRoute: typeof ExperienceCompanyRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  WritingSlugRoute: typeof WritingSlugRoute
  ExperienceIndexRoute: typeof ExperienceIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  WritingIndexRoute: typeof WritingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_redirects': {
      id: '/_redirects'
      path: '/_redirects'
      fullPath: '/_redirects'
      preLoaderRoute: typeof RedirectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now': {
      id: '/now'
      path: '/now'
      fullPath: '/now'
      preLoaderRoute: typeof NowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/': {
      id: '/experience/'
      path: '/experience'
      fullPath: '/experience/'
      preLoaderRoute: typeof ExperienceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/$company': {
      id: '/experience/$company'
      path: '/experience/$company'
      fullPath: '/experience/$company'
      preLoaderRoute: typeof ExperienceCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  RedirectsRoute: RedirectsRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  NowRoute: NowRoute,
  ExperienceCompanyRoute: ExperienceCompanyRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  WritingSlugRoute: WritingSlugRoute,
  ExperienceIndexRoute: ExperienceIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  WritingIndexRoute: WritingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
